components:
    schemas:
        Segment:
            description:
                Represents a set of users that meet certain criteria. Segments may be used to create customized
                experiences for users.
            properties:
                active:
                    description:
                        A flag that indicates whether the segment is active.
                    readOnly: true
                    type: boolean
                criteria:
                    description:
                        The segment's criteria.
                    readOnly: true
                    type: string
                criteriaValue:
                    additionalProperties:
                        type: object
                    description:
                        The segment's criteria in JSON.
                    readOnly: true
                    type: object
                dateCreated:
                    description:
                        The segment's creation date.
                    format: date-time
                    readOnly: true
                    type: string
                dateModified:
                    description:
                        The segment's most recent modification date.
                    format: date-time
                    readOnly: true
                    type: string
                id:
                    description:
                        The segment's ID.
                    format: int64
                    readOnly: true
                    type: integer
                name:
                    description:
                        The segment's name.
                    readOnly: true
                    type: string
                siteId:
                    description:
                        The ID of the segment's site.
                    format: int64
                    readOnly: true
                    type: integer
                source:
                    description:
                        The segment's source.
                    readOnly: true
                    type: string
            required:
                - criteria
                - name
            type: object
info:
    description:
        "A Java client JAR is available for use with the group ID 'com.liferay', artifact ID
        'com.liferay.headless.admin.user.client', and version '4.0.34'."
    license:
        name: "Apache 2.0"
        url: "http://www.apache.org/licenses/LICENSE-2.0.html"
    title: "Headless Admin User"
    version: v1.0
openapi: 3.0.1
paths: